#cloud-config
autoinstall:
  version: 1
  timezone: "{{TIMEZONE}}"
  storage:
    layout:
      name: lvm
      sizing-policy: all
      password: "{{LUKS_PASSWORD}}"
  locale: "{{LOCALE}}"
  codecs:
    install: true
  drivers:
    install: true
  oem:
    install: true
  keyboard:
    layout: "{{KEYBOARD_LAYOUT}}"
    variant: ""
  refresh-installer:
    update: false
  apt:
    preserve_sources_list: true
  source:
    id: ubuntu-desktop
  packages: []
  snaps: []
  updates: security
  shutdown: poweroff
  
