name: Validate Autoinstall Config

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  validate-autoinstall:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Python build toold
      run: |
        python -m pip install --upgrade pip setuptools wheel jsonschema yaml

    - name: Clone Subiquity repository
      run: |
        git clone https://github.com/canonical/subiquity.git

    - name: Install dependencies
      run: |
        cd subiquity
        make install_deps

    - name: Replace autoinstall.yaml placeholders
      run: |
        cp autoinstall.yaml subiquity/
        cd subiquity
        sed -i 's/{{TIMEZONE}}/UTC/' ./autoinstall.yaml
        sed -i 's/{{LUKS_PASSWORD}}/password123/' ./autoinstall.yaml
        sed -i 's/{{LOCALE}}/en_US.UTF-8/' ./autoinstall.yaml
        sed -i 's/{{KEYBOARD_LAYOUT}}/us/' ./autoinstall.yaml
        sed -i 's/{{COMPANY_NAME}}/MyCompany/' ./autoinstall.yaml

    - name: Validate autoinstall.yaml
      run: |
        cd subiquity
        scripts/validate-autoinstall-user-data.py ../autoinstall.yaml

    - name: Validation successful
      run: echo "✅ Autoinstall configuration validated successfully!"
