name: Validate autoinstall.yaml

on:
  push:
    paths:
      - 'autoinstall.yaml'
  pull_request:
    paths:
      - 'autoinstall.yaml'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cloud-init

      - name: Validate autoinstall.yaml
        run: |
          cloud-init schema --config-file autoinstall.yaml
