name: Shell Script Linter

on:
  push:
    paths:
      - 'make-image.sh'
  pull_request:
    paths:
      - 'make-image.sh'

jobs:
  lint-shell-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Run shellcheck
        run: shellcheck make-image.sh
